# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NiamR2igadQhd8HxeTpIuOjRzr2BDgAd
"""

import random

def main():
    i = 1
    Aprob = 0
    NoAprob = 0

    materias = ["Programación", "Estructuras discretas", "Matematica", "Computación", "Computación y sociedad", "Humanismo"]
    materia = random.choice(materias)

    print("Ingrese el número de estudiantes del curso")
    n = int(input())

    while i <= n:
        nombres = ["Juan", "Ana", "Carlos", "María", "Pedro", "Luisa", "Miguel", "Elena"]
        apellidos = ["Gómez", "Fernández", "Martínez", "López", "Pérez", "Rodríguez", "Sánchez"]

        nombreAleatorio = random.choice(nombres)
        apellidoAleatorio = random.choice(apellidos)
        nombre = f"{nombreAleatorio} {apellidoAleatorio}"
        cedula = str(random.randint(0, 1000000000))

        acd = int(random.random() * 10 + 1)
        ape = int(random.random() * 10 + 1)
        aa = int(random.random() * 10 + 1)

        ACD = acd * 0.35
        APE = ape * 0.35
        AA = aa * 0.30
        porcentaje_acumulado = ACD + APE + AA

        # Verificar aprobación
        if porcentaje_acumulado >= 7:
            print(f"Estudiante: {nombre}")
            print(f"Con numero de cedula: {cedula}")
            print(f"Ha aprobado la materia: {materia}")
            Aprob += 1
        else:
            print(f"Estudiante: {nombre}")
            print(f"Con numero de cedula: {cedula}")
            print(f"No ha aprobado la materia: {materia}")
            print("Deberá rendir un examen de recuperación calificado sobre 3.5/10.")
            NoAprob += 1

        i += 1

    print("ESTADISTICAS DEL CURSO")
    print(f"Estudiantes aprobados: {Aprob}")
    print(f"Estudiantes no aprobados: {NoAprob}")

if __name__ == "__main__":
    main()