# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15atlt0_dUHaP1-6t1Y3tDK5qWjrbVkZu
"""

import random

class Jugador:
    def __init__(self, nombre, posicion, edad):
        self.nombre = nombre
        self.posicion = posicion
        self.edad = edad
        self.goles = 0

def generarEquipo(nombreEquipo, numJugadores):
    equipo = []
    for i in range(1, numJugadores + 1):
        jugador = Jugador(nombreEquipo + str(i), "Posición" + str(i), 20 + i)
        equipo.append(jugador)
    return equipo

def simularPartido(equipo):
    goles = 0
    for jugador in equipo:
        golesJugador = random.randint(0, 3)
        jugador.goles = golesJugador
        goles += golesJugador
    return goles

def mostrarEstadisticas(golesEquipoA, golesEquipoB):
    print("ESTADÍSTICAS DEL PARTIDO:")
    print("Goles Equipo A: " + str(golesEquipoA))
    print("Goles Equipo B: " + str(golesEquipoB))

equipoA = generarEquipo("A", 3)
equipoB = generarEquipo("B", 3)

golesEquipoA = simularPartido(equipoA)
golesEquipoB = simularPartido(equipoB)

mostrarEstadisticas(golesEquipoA, golesEquipoB)

if golesEquipoA == golesEquipoB:
    print("Empate. Se simularán los penales.")
    # Aquí puedes simular la tanda de penales y actualizar los resultados
else:
    equipoGanador = "Equipo A" if golesEquipoA > golesEquipoB else "Equipo B"
    print("Equipo ganador: " + equipoGanador)