# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_xrRerZxhgDuTmm8gNyqJwnoEVdcbCrq
"""

loes1 = True
loes2 = False
num12 = 0
num13 = 1
num17 = 0
serie = 0
acumulador = 2
numeroOpcion = 0
juego = ""
numeroOpcion2 = ""
numero_generado = 20
loes1 = True
serie = 0
num12 = 0
num13 = 1
acumulador = 2
veces = 11

print('Intenta adivinar el numero')
while juego != 'no':
    print('Adivine el numero:')
    numero_user = int(input())

    while numero_generado != numero_user and veces > 1:
        print('INCORRECTO!, QUIERES UNA PISTA? (si/no)')
        print('RECUERDA QUE SI TE DOY UNA PISTA SE TE RESTA UN INTENTO')
        numeroOpcion2 = input()

        if numeroOpcion2 == 'si':
            veces -= 1
            print("Selecciona la pista que quieres ver:")
            print("[1] Saber si el numero es mayor o menor")
            print("[2] Saber si el numero es par o impar")
            print("[3] Saber si el numero es o no primo")
            print("[4] Saber si el numero pertenece a la serie de fibonacci")
            print("[5] Saber si el numero es multiplo de n")
            numeroOpcion = int(input())

            if numeroOpcion == 1:
                if numero_generado > numero_user:
                    print('EL NUMERO ES MAYOR AL QUE INGRESASTE')
                else:
                    print('EL NUMERO ES MENOR AL QUE INGRESASTE')

            elif numeroOpcion == 2:
                if numero_generado % 2 == 0:
                    print('EL NUMERO ES PAR')
                else:
                    print('EL NUMERO ES IMPAR')

            elif numeroOpcion == 3:
                if numero_generado == 1:
                    print('EL NUMERO NO ES PRIMO')
                else:
                    while acumulador < numero_generado:
                        if numero_generado % acumulador == 0:
                            loes1 = False
                        acumulador += 1

                    if loes1:
                        print('EL NUMERO ES PRIMO')
                    else:
                        print('EL NUMERO NO ES PRIMO')

            elif numeroOpcion == 4:
                while serie < numero_generado:
                    num17 = num12
                    num12 = num13
                    num13 = num17 + num13
                    serie = num12

                if serie == numero_generado:
                    loes2 = True
                else:
                    loes2 = False

                if loes2:
                    print('EL NUMERO PERTENECE A LA SERIE DE FIBONACCI')
                else:
                    print('EL NUMERO NO PERTENECE A LA SERIE DE FIBONACCI')

            elif numeroOpcion == 5:
                if numero_generado % 3 == 0:
                    print('EL NUMERO ES MULTIPLO DE 3')
                elif numero_generado % 5 == 0:
                    print('EL NUMERO ES MULTIPLO DE 5')
                elif numero_generado % 7 == 0:
                    print('EL NUMERO ES MULTIPLO DE 7')
                elif numero_generado % 11 == 0:
                    print('EL NUMERO ES MULTIPLO DE 11')
                elif numero_generado % 12 == 0:
                    print('EL NUMERO ES MULTIPLO DE 12')
                else:
                    print('Opcion incorrecta, que no vez las opciones o que????')

        veces -= 1
        print('Te quedan', veces, 'intentos!')
        numero_user = int(input())

    if numero_generado == numero_user:
        print('Exacto adivinaste en:', 11 - veces, 'intentos.')
    else:
        print('perdiste')
        print('El numero era:', numero_generado)

    print('Deseas seguir jugando? (si/no)')
    juego = input()

print('Nos vemos')